export const SAVE_PLAYERS_NAME = "SAVE_PLAYERS_NAME";
export const SAVE_PLAYERS_OPTION = "SAVE_PLAYERS_OPTION";
export const SAVE_WINNER = "SAVE_WINNER";
export const SAVE_ROUND = "SAVE_ROUND";
export const RESET_GAME = "RESET_GAME";
export const DRAW_ROUND = "DRAW_ROUND";